influx/querybuilder.go, influx/querybuilder_test.go
=> querybuilder is stateless

mongo/document/paranoid.go
Related to Scalingo/autoscaler-service#58
The problem I try to solve here is the following. We set the `DeletedAt` field json tag with `omitempty`. However it can't work as the `time.Time` type is a structure. 
Hence, when marshaling a structure with paranoid:
```go
type Scaler struct {
DeletedAt time.Time `json:"deleted_at,omitempty"`
LastScale time.Time `json:"last_scale,omitempty"`
}
func main() {
s := &Scaler{}
j, _ := json.Marshal(s)
fmt.Printf("JSON: %+v\n", string(j))
}
```
we get the following output:
```text
JSON: {"deleted_at":"0001-01-01T00:00:00Z","last_scale":"0001-01-01T00:00:00Z"}
```
But we don't want to send the `DeletedAt` field if it has a zero value. Defining it as a pointer of `time.Time` fixes this issue.
=> DeletedAt is a pointer to time.Time

.gitignore, gomock_generator/README.md, gomock_generator/gomockgenerator/generate.go, gomock_generator/gomockgenerator/package.go, gomock_generator/main.go
```text
$ gomock_generator -h                                                  
NAME:
Gomock generator - Highly parallelized generator of gomock mocks
USAGE:
gomock_generator [global options] command [command options] [arguments...]
VERSION:
0.1.0
COMMANDS:
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--base-package value           Project base package. E.g. github.com/Scalingo/go-utils. [$BASE_PACKAGE]
--mocks-filename value         Filename of the JSON file containing the MockConfiguration. Location of this file is the base package. (default: "mocks.json") [$MOCKS_FILENAME]
--signatures-filename value    Filename of the signatures cache. Location of this file is the base package. (default: "mocks_sig.json") [$SIGNATURES_FILENAME]
--concurrent-goroutines …
```
=> GoMock generator CLI

mongo/mongo.go
`mongodb://localhost:27017/db?ssl=true&option=value`
should not become
mongodb://localhost:27017/db&option=value
but
mongodb://localhost:27017/db?&option=value
which is valid
=> The ? mark should not be removed when parsing ssl/timeout

influx/querybuilder.go, influx/querybuilder_test.go
Related to Scalingo/metrics-storage-service#66
=> Measurement must be between double quotes to prevent issues with measurement name which contains character such as dash

mongo/document/validation_error.go
=> Use strings.Join to prevent trailing comma

CHANGELOG.md, mongo/document/paranoid.go, mongo/document/paranoid_test.go
=> IsDeleted returns true if DeletedAt is not zero

storage/s3.go, storage/s3_test.go, storage/swift.go
If you agree with the issue, fixes #91
=> [S3] Trim left slashes

mongo/document/document.go
Those values are already pointers, we should not take the pointer value instead, i have no idea why this works on amd64/i386
=> Fix: document Create/Save failed on arm due to serialization errors on arm64

.gitignore, errors/validation_errors.go, errors/validation_errors_test.go
=> Fix validation errors builder string

tarball/archive.go
It had quite a lot of impact in tar operations in production with large tarball
=> Buffer size of 512MB is not a good idea, it was supposed to be 512kB

CHANGELOG.md, Gopkg.lock, Gopkg.toml, storage/swift.go
All our projects have been updated to use the new `ApplyEnvironment` function. For now this project is only used in appsdeck-run and we forgot to update this project in the process.
BTW we need to make use of this in all the project using an object storage IMHO.
It breaks the API so it would require a new major version.
Related to https://github.com/Scalingo/appsdeck-run/issues/86
=> Use the new ApplyEnvironment function for Swift

storage/swift.go
I think this is an issue with github.com/ncw/swift. I may open an issue there to clarify with them. The [documentation](https://pkg.go.dev/github.com/ncw/swift?tab=doc#Connection.Authenticate) about the `Authenticate` method states:
>  If you don't call it before calling one of the connection methods then it will be called for you on the first access. 
Hence, I assumed it's not necessary on our side to call the `Authenticate` method. But when we do that, there is a nil pointer exception:
```
github.com/Scalingo/appsdeck-run/vendor/github.com/ncw/swift.(*Connection).storage(0xc0005be540, 0xc00003c1c4, 0x14, 0xc00044a2a0, 0x5b, 0xf54736, 0x4, 0x0, 0x0, 0xc00033c840, ...)
/opt/go/services/appsdeck-run/src/github.com/Scalingo/appsdeck-run/vendor/github.com/ncw/swift/swift.go:816 +0x7d …
```
=> [storage] Authenticate the connection to Swift

gomock_generator/gomockgenerator/package.go
Before:
```
└> gomock_generator
INFO[2020-08-17T15:32:41.525] Configuration for this mocks generation       concurrent_goroutines=4 mocks_file_path=./mocks.json signatures_filename=mocks_sig.json
INFO[2020-08-17T15:32:41.526] Generating 129 mocks                          base_package=github.com/Scalingo/appsdeck-database nb_mocks=129
ERRO[2020-08-17T15:32:41.587] fail to get interface hash: fail to get interface signature for Client: fail to parse package: open /home/leo/go/src/github.com/influxdata/influxdb/client/v2: no such file or directory  nb_mocks=129
```
After:
```
└> gomock_generator
INFO[2020-08-17T15:44:49.631] Configuration for this mocks generation       concurrent_goroutines=4 mocks_file_path=./mocks.json signatures_filename=mocks_sig.json
INFO[2020-08-17T15:44:49.632] …
```
=> Take vendor dir into account when generating mocks

gomock_generator/main.go
Fixes https://github.com/Scalingo/go-utils/issues/117
=> Validate that goimports and mockgen executables are presents, otherwise installing them

concurrency/README.md, concurrency/parallel_worker.go, concurrency/parallel_worker_example_test.go
FYI 'go test' execute the Example and compare the output as the comment // Output: [...]
=> Add package 'concurrency' with struct ParallelWorker, include doc and example as test

gomock_generator/gomockgenerator/generate.go
The following situation wasn't working, it is now working as expected.
Director $GOPATH/src/github.com/Scalingo/package
```
/mocks.json
/client.go
```
```json
{
"package": "github.com/Scalingo/package",
"mocks": [
{
"Interface": "Client"
}
]
}
```
Result after gomock_generator:
```
/mocks.json
/mocks_sig.json
/client.go
/packagemock/client_mock.go
```
=> Allow empty SrcPackage for a mock

mongo/CHANGELOG.md, mongo/document/document.go
=> fix(mongo): Display the mongodb object id in the correct format on the logs

storage/CHANGELOG.md, storage/s3.go, storage/s3_test.go
This reverts commit e8eaca7380b8ae24975c3033a3b51cfd67518f76.
This is a regression due to my local s3 client version.
=> Revert "fix(storage): NotFoundErrCode should be 404 not a string 'NotFound'"

logger/plugins/rollbarplugin/README.md
The Rollbar plugin requires to be registered before instantiating the logger.
=> docs(readme): instructions to register the rollbarplugin

errors/CHANGELOG.md, errors/cause.go, errors/cause_test.go, errors/errctx.go, errors/errgo.go, errors/errors.go
This PR adds a `New` method to ErrCtx
Also, make the `RootCause` and `IsRootCause` to unwrap underlying errors.
To see an example of its implementation, you can check these PRs:
- https://github.com/Scalingo/metrics-storage-service/pull/146
- https://github.com/Scalingo/logs-archive-service/pull/135
Fix #442
=> feat(errors): add method New to ErrCtx

nsqconsumer/CHANGELOG.md, nsqconsumer/consumer.go, nsqconsumer/go.mod, nsqconsumer/go.sum
This PR in `nsqconsumer` package the implementation of ErrCtx to get context logger and be able to manage `noRetry` field correctly if the `Error` is wrapped
Fix #447
=> feat(nsqconsumer): log the error by using root context (ErrCtx)

nsqconsumer/CHANGELOG.md, nsqconsumer/README.md
=> Bump nsqconsumer to v1.2.0: better error management

io/copier.go, io/copier_test.go, io/go.mod, io/go.sum
The current test is flakky. From past failed executions, it can go up to 230MB. Let's remove this test.
Fix #548
=> n/a, only test changes
=> test(io): don't check the exact system cache size

errors/CHANGELOG.md, errors/cause.go, errors/cause_test.go, errors/errctx.go, graceful/main_test.go
I'm proposing to deprecate `IsRootCause(err, errWithExpectedType)` and `if(errors.RootCause(err) == something` to use `errors.As(err, errWithExpectedType)` and `errors.Is(err, something)`, to match idiomatic Go practices
Fixes #582
=> feat(Is/As) Match API from standard library and leverage it to check for error value of type

etcd/CHANGELOG.md, etcd/README.md
In order to release security fix from https://github.com/Scalingo/go-utils/pull/785
=> [etcd] Bump v1.1.2

errors/CHANGELOG.md, errors/errctx.go
=> docs(errors): deprecate use of `errgo` in `ErrCtx`

graceful/go.mod
Related to [swan-agent PR#36](https://github.com/Scalingo/swan-agent/pull/36)
=> Remove go patch version from go.mod (1.22.4 => 1.22)

graceful/CHANGELOG.md, graceful/README.md, graceful/service.go, graceful/service_signals.go, graceful/service_test.go, graceful/testdata/cmd/server/server.go
Prerequisite to fix sand issue: https://github.com/Scalingo/sand/issues/271 (since graceful v1.1.2)
Related to PR #909
Related to Story STORY-828
=> feat: handle multiple http servers with one graceful service

nsqconsumer/CHANGELOG.md, nsqconsumer/consumer.go
=> feat(nsqconsumer): add a configurable log level

mongo/CHANGELOG.md, mongo/document/base.go, mongo/document/document.go, mongo/document/document_test.go
=> package(mongo) Do not break API to handle validation errors with internal errors

logger/CHANGELOG.md, logger/logger.go
This PR removes the recent addition of a custom type. It instead uses the string type for the loggerContextKey
A bug was introduced because the string and the custom type (with underlying string type) are not treated as the same type.
=> fix(logger): Remove custom type from logger context key

nsqconsumer/CHANGELOG.md, nsqconsumer/consumer.go
=> Use github.com/Scalingo/go-utils/logger API instead of injecting logger manually in context

logger/CHANGELOG.md, logger/loggable.go, logger/loggable_test.go
=> feat(logger): add support for `log` tags

nsqconsumer/CHANGELOG.md, nsqconsumer/consumer.go
=> [STORY-1378] Allow getting internal data of nsqconsumer.Error for better testability

otel/go.mod, otel/metrics.go
=> feat(otel): create a meter

otel/CHANGELOG.md, otel/otel.go
=> fix(otel): Use OTEL_METRIC_EXPORT_INTERVAL instead of OTEL_COLLECTION_INTERVAL env var

graceful/service.go, graceful/service_test.go, logger/CHANGELOG.md
This PR fixes issue #1122 identified by semgrep, where a mutex lock might not be released
=> fix(graceful): VULN Defer mutex unlock + lint

graceful/CHANGELOG.md, logger/CHANGELOG.md
This PR fixes an error merged in the PR #1123 where the incorrect changelog was updated.
=> fix(graceful/logger): revert erroneous changelog update

otel/CHANGELOG.md, otel/otel.go
Fix https://github.com/Scalingo/go-utils/issues/1165
=> fix(otel): add OTEL_SDK_DISABLED env var

errors/CHANGELOG.md, errors/cause.go, errors/cause_test.go, errors/errctx.go, errors/errctx_test.go
The PR #1207 introduces a breaking change, which leads to a new major version. This is a perfect time to remove the deprecated methods we have in this library.
=> refactor(errors): remove deprecated functions

errors/CHANGELOG.md, errors/validation_errors.go, errors/validation_errors_test.go
=> fix(errors): `Build` returns `error` not `*ValidationErrors`

.github/CODEOWNERS
I wonder whether the issue reported by @brandon-welsch  [here](https://scalingo.slack.com/archives/C01PFD3GBU7/p1752591610697449) is not because of this. That's what I understand from the error reported on this page: https://github.com/Scalingo/go-utils/network/updates/15269090/jobs
=> build(codeowners): for `.github/*` rather than `.github/workflows/*` which does not exist in this repository

.github/dependabot.yml, README.md
Fix #1234
Some modules like `otel` and other ones was not tracked in the dependabot config. I added it
=> fix(dependabot): Add missing modules to dependabot config

.github/dependabot.yml
We try to configure Dependabot to ignore this Dependency. For some reason, the previous configuration (#1236) didn't work (#1251). Let's try to configure this without specifying the version to see if it works...
=> build(dependabot): ignore `github.com/aws/aws-sdk-go-v2` without version specified

otel/CHANGELOG.md, otel/go.mod, otel/go.sum, otel/otel.go
=> build(deps): Bump github.com/Scalingo/go-utils/errors from v2.5.1 to v3.0.0

errors/CHANGELOG.md, errors/cause.go, errors/cause_test.go
=> feat(errors/unwrapError) it now unwraps errors which implement Unwrap() method

errors/CHANGELOG.md, errors/cause.go, errors/errctx.go
After `UnwrapError` (essentially used by nsqconsumer), here the update of `RootCtxOrFallback` that is used by go-handlers.
=> feat(errors/errctx) RootCtxOrFallback is now retro compatible
