etcd/client.go
etcd/config.go

package 'etcd', ability to create config and client for etcdv3 from the environment

---

mongo/document/base.go
mongo/document/document.go
mongo/document/paranoid.go
mongo/document/validation_error.go
mongo/document/validation_test.go

Add validable interface

---

mongo/document/base_test.go
mongo/document/document.go

Add FindSort method

---

mongo/document/paranoid.go
mongo/document/paranoid_test.go

Add restore

---

mongo/document/base_test.go
mongo/document/document.go

Remove FindSort and FindSortUnscoped, accept variatic arguments in Find, FindUnscoped and FindOne instead

---

publicgen/ast.go
publicgen/generator.go
publicgen/reflect.go

Add pugblicgen

---

influx/doc.go
influx/execute.go
influx/querybuilder.go
influx/querybuilder_test.go

Related to Scalingo/scalingo-alerter-service#21

Add InfluxDB query builder

---

influx/doc.go
influx/querybuilder.go
influx/querybuilder_test.go

Add influx.String method

---

Gopkg.lock
env/map.go
nsqlbproducer/env.go
nsqlbproducer/lbproducer.go
nsqlbproducer/lbproducer_test.go
nsqproducer/env.go
nsqproducer/lbproducer.go
nsqproducer/nsqproducermock/gomock_producer.go
nsqproducer/producer.go

Load balance nsq producers

---

nsqlbproducer/lbproducer.go
nsqlbproducer/lbproducer_test.go

Implement fallback mode, producing always to the same producer except in case of failure

---

nsqlbproducer/env.go
nsqproducer/env.go

Add Logger as argument to nsqlbproducer.FromEnv

---

influx/querybuilder.go
influx/querybuilder_test.go

Fix loop through all the conditions

---

mongo/document/document.go

Add the ability to get mgo.Query instead of results directly to let clients implement pagination for instance

---

nsqlbproducer/env.go

[nsqlbproducer] forward skip log set

---

mongo/document/document.go

Fix iter error to return iterator error and not callback error

---

mongo/mongo.go

(to connect to multiple databases for instance)

Make mongo pacakge reusable with custom URL

---

gomock_generator/gomockgenerator/generate.go
gomock_generator/gomockgenerator/package.go
gomock_generator/main.go

Various fixes for gomock generator

---

gomock_generator/gomockgenerator/generate.go
gomock_generator/gomockgenerator/package.go

Do not panic on nested interfaces

---

mongo/mongo.go

That's what is done by default in:
mgo.Dial() -> internals are adding a timeotu of 10 seconds

[mongodb] Add a default connection timeout of 10 seconds

---

influx/execute.go
influx/querybuilder.go
influx/querybuilder_test.go

Add support for subqueries

---

errors/cause.go
errors/cause_test.go
errors/validation_errors.go
mongo/document/validation_error.go

Related to Scalingo/go-handlers#15

Better handling of ValidationErrors

---

retry/retry.go
retry/retry_test.go

Add a retryer interface

---

retry/README.md

[README] Instructions to use the retryer

---

gomock_generator/README.md

GoMockGenerator, add an 'installation troubleshooting' section

---

fs/README.md
fs/fs.go
fs/go.mod
fs/go.sum

Needed for https://github.com/Scalingo/go-utils/pull/121

Externalize 'fs' package from private project

---

gomock_generator/gomockgenerator/generate.go
gomock_generator/gomockgenerator/package.go

Fix a bug where gomock will generate mocks in a github.com directory

Add support for nested interfaces

---

mongo/go.mod
mongo/pagination/README.md
mongo/pagination/pagination.go
mongo/pagination/pagination_test.go

A pagination method to follow [scalingo pagination](https://developers.scalingo.com/index#pagination)
Related to [GRR-81]
[GRR-81]: https://scalingo.atlassian.net/browse/GRR-81

[Mongo] Add scalingo pagination support to the package

---

.github/dependabot.yml

Related to [SG-49]
[SG-49]: https://scalingo.atlassian.net/browse/SG-49

[Dependabot] Attempt to support all Go Modules

---

.github/dependabot.yml

Related to [SG-49]
[SG-49]: https://scalingo.atlassian.net/browse/SG-49

[Dependabot] Enable on all Go Modules

---

mongo/CHANGELOG.md
mongo/pagination/README.md
mongo/pagination/pagination_by_cursor.go
mongo/pagination/pagination_by_cursor_test.go
mongo/pagination/pagination_test.go

Related to [SG-72]
[SG-72]: https://scalingo.atlassian.net/browse/SG-72

Add pagination by cursor

---

gomock_generator/gomockgenerator/package.go

I don't understand the TODO so I can't open an issue based on it

fix: remove TODO

---

nsqlbproducer/lbproducer.go
nsqlbproducer/lbproducer_test.go

Fix #210
Related to [SRE-86]
[SRE-86]: https://scalingo.atlassian.net/browse/SRE-86

feature(nsqlbproducer) Add timeouts when publishing message

---

graceful/service_test.go
influx/CHANGELOG.md
influx/querybuilder.go
influx/querybuilder_test.go

- Depreciation of `Field` function
- Creation of specific field functions

[Influx] Specify querybuilder field functions

---

logger/logger.go

feat(logger): Add helpers to add fields and context in one call

---

storage/CHANGELOG.md
storage/backend.go
storage/go.mod
storage/go.sum
storage/mocks.json
storage/mocks_sig.json
storage/s3.go
storage/s3_test.go
storage/storagemock/backend_mock.go
storage/swift.go
storage/types/types.go

`Info` method returns `ObjectNotFound` custom error in case of object not found

feat(storage): Add Info method returns object information from header

---

README.md
storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.2.0

---

storage/CHANGELOG.md
storage/s3.go
storage/s3_test.go

In addition, some tests have been added.
Fix #401

fix(s3.Info): no attribution for Content-Type and Checksum if nil pointers

---

mongo/CHANGELOG.md
mongo/mongo.go

This PR follows the discussion in #396

docs(mongo): add doc for Session function

---

.sclng/metadata.toml

chore(asgard): add asgard to the project

---

storage/CHANGELOG.md

chore(changelog): edited changelogs

---

storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.3.1

---

storage/CHANGELOG.md
storage/backend.go
storage/s3.go
storage/s3_test.go
storage/swift.go

feat(storage): `Delete` may return `ObjectNotFound`

---

storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.3.2

---

errors/CHANGELOG.md
errors/README.md
errors/go.mod

[errors] Bump v2.0.0

---

cronsetup/CHANGELOG.md
etcd/CHANGELOG.md
fs/CHANGELOG.md
storage/CHANGELOG.md
tarball/CHANGELOG.md

docs(changelog): add Dependabot missing entries

---

errors/CHANGELOG.md
errors/cause.go
errors/cause_test.go
nsqconsumer/consumer.go

Related to https://github.com/Scalingo/go-utils/issues/447

feat(errors): Add Unwrap function

---

errors/CHANGELOG.md
errors/README.md

[errors] Bump v2.2.0

---

errors/CHANGELOG.md
errors/cause_test.go
errors/errctx.go

fix(errctx): remove NoteMask, `Notef` should be use instead

---

mongo/CHANGELOG.md
mongo/document/validation_error.go
mongo/go.mod
mongo/go.sum

Bump go-utils/errors to v2

---

mongo/CHANGELOG.md
mongo/README.md

Bump Scalingo/go-utils/mongo to v1.2.2

---

mongo/CHANGELOG.md
mongo/document/document.go
mongo/document/paranoid_test.go

feat(count): Add count method to document package

---

mongo/CHANGELOG.md
mongo/README.md

Realease adding Count and CountUnscoped method to mongo/document package

bump: release mongo 1.3.0

---

mongo/CHANGELOG.md
mongo/document/document.go

fix(mongo): Close mongo session on CountUnscoped

---

mongo/CHANGELOG.md
mongo/README.md

[mongo] Bump v1.3.1

---

errors/CHANGELOG.md
errors/README.md

[errors] Bump v2.3.0

---

httpclient/go.mod
httpclient/go.sum
httpclient/httpclient.go
nsqproducer/go.mod
nsqproducer/go.sum
nsqproducer/producer.go

build(deps): bump github.com/gofrs/uuid

---

storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.3.3

---

README.md
errors/CHANGELOG.md
errors/README.md

[errors] Bump v2.4.0

---

graceful/CHANGELOG.md
graceful/README.md

[graceful] Bump v1.1.2

---

graceful/CHANGELOG.md
graceful/README.md

[graceful] Bump v1.1.3

---

graceful/CHANGELOG.md
graceful/README.md

Related to:
* STORY-828
* https://github.com/Scalingo/sand/issues/271

[graceful] Bump v1.2.0

---

pagination/CHANGELOG.md
pagination/README.md

[pagination] Bump v1.0.0

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.3.0

---

logger/CHANGELOG.md
logger/README.md

[logger] Bump v1.3.0

---

mongo/CHANGELOG.md
mongo/README.md

[mongo] Bump v1.4.0

---

logger/CHANGELOG.md
logger/README.md

[logger] Bump v1.3.1

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.3.1

---

logger/CHANGELOG.md
logger/README.md

[logger] Bump v1.4.0

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.3.2

---

nsqconsumer/CHANGELOG.md
nsqconsumer/consumer.go

You can have a look at the individual commits for the details.

refactor(consumer): match our current best practices around logging and errors

---

otel/LICENSE

docs(otel): Add missing LICENSE file to otel package

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.3.3

---

otel/otel.go

fix(otel): check if endpoint is defined

---

otel/otel_test.go

fix(otel): tests for exporter endpoint

---

storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.4.0

---

storage/CHANGELOG.md
storage/go.mod
storage/go.sum
storage/s3.go

chore(deps) Update deps, use go-utils/errors, configure request/response checksum

---

storage/s3.go

fix(storage/s3) Correctly use AWS SDK to configure custom endpoint - Related to #1060

---

storage/CHANGELOG.md
storage/README.md

[storage] Bump v1.5.1

---

logger/CHANGELOG.md
logger/plugins/rollbarplugin/rollbar_plugin.go

feat(logger) add rollbar plugin close wrapper

---

logger/plugins/rollbarplugin/README.md

feat(logger) update readme related to close wrapper

---

nsqconsumer/CHANGELOG.md
nsqconsumer/consumer.go

feat(disable-backoff) Add ability to completely disable backoff

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.4.0

---

nsqconsumer/CHANGELOG.md
nsqconsumer/consumer.go

fix(nsqconsumer/disable-backoff) Correctly take option into account

---

publicgen/CHANGELOG.md
publicgen/README.md

[publicgen] Bump v1.1.0

---

nsqproducer/CHANGELOG.md
nsqproducer/README.md

[nsqproducer] Bump v1.3.0

---

nsqlbproducer/CHANGELOG.md
nsqlbproducer/README.md

[nsqlbproducer] Bump v1.2.0

---

logger/CHANGELOG.md
logger/README.md

[logger] Bump v1.6.0

---

influx/CHANGELOG.md
influx/README.md

[influx] Bump v1.3.0

---

gomock_generator/CHANGELOG.md
gomock_generator/README.md

[gomock_generator] Bump v1.4.0

---

env/CHANGELOG.md
env/README.md

[env] Bump v1.2.0

---

etcd/CHANGELOG.md
etcd/README.md

[etcd] Bump v1.2.0

---

retry/CHANGELOG.md
retry/README.md

[retry] Bump v1.2.0

---

.github/CODEOWNERS
concurrency/go.mod
cronsetup/go.mod
crypto/go.mod
difflib/go.mod
env/go.mod
errors/go.mod
etcd/go.mod
fs/go.mod
gomock_generator/go.mod
graceful/go.mod
httpclient/go.mod
influx/go.mod
io/go.mod
logger/go.mod
mongo/go.mod
nsqconsumer/go.mod
nsqlbproducer/go.mod
nsqproducer/go.mod
otel/docs/examples/int64-async-gauge/go.mod
otel/docs/examples/int64-sync-counter/go.mod
otel/go.mod
pagination/go.mod
postgresql/go.mod
publicgen/go.mod
retry/go.mod
security/go.mod
storage/go.mod
tarball/go.mod

1.24.3 was too strict and created issues in our CI/CD pipelines

[STORY-2085] Regress to Go 1.24

---

concurrency/go.mod
concurrency/go.sum
cronsetup/go.mod
cronsetup/go.sum
gomock_generator/go.mod
gomock_generator/go.sum
graceful/go.mod
graceful/go.sum
mongo/go.mod
mongo/go.sum
nsqconsumer/go.mod
nsqconsumer/go.sum
nsqlbproducer/go.mod
nsqlbproducer/go.sum
nsqproducer/go.mod
nsqproducer/go.sum
storage/go.mod
storage/go.sum
tarball/go.mod
tarball/go.sum

build: Go 1.24.3 to 1.24

---

otel/CHANGELOG.md
otel/README.md

[otel] Bump v0.4.0

---

retry/CHANGELOG.md
retry/README.md

[retry] Bump v1.2.2

---

otel/CHANGELOG.md
otel/README.md

[otel] Bump v0.5.0

---

logger/CHANGELOG.md
logger/README.md
logger/go.mod

[logger] Bump v1.9.1

---

otel/CHANGELOG.md
otel/go.mod
otel/otel.go

fix(otel): Enforce TLS connections, use allowlisted ciphers and TLS v1.2 at least in production/staging environments

---

otel/CHANGELOG.md
otel/README.md

Fix https://github.com/Scalingo/project-items/issues/879

[otel] Bump v0.6.0

---

errors/CHANGELOG.md
errors/README.md

[errors] Bump v3.1.0

---

nsqconsumer/CHANGELOG.md
nsqconsumer/consumer.go

fix(nsqconsumer/errors) make unwrap compatible with all go-utils/errors versions

---

nsqconsumer/CHANGELOG.md
nsqconsumer/README.md

[nsqconsumer] Bump v1.5.3

---

.github/CODEOWNERS

build(CODEOWNERS): assign IST for Dependabot's PRs

---

errors/cause_test.go
otel/CHANGELOG.md
otel/otel.go
otel/otel_test.go

[STORY-2516] Add ability to define global attributes from caller with an option, including an helper to define Service Version

---

otel/CHANGELOG.md
otel/README.md

[otel] Bump v0.8.0
